# Generated by Django 2.0.2 on 2018-02-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=100)),
                ('user_image', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_at', models.FloatField(default=1519460100.9442601)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=100)),
                ('user_image', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('create_at', models.FloatField(default=1519460100.9447603)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=50)),
                ('admin', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('create_at', models.FloatField(default=1519460100.9432595)),
            ],
        ),
    ]
