# Generated by Django 2.0.2 on 2018-02-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_at',
            field=models.FloatField(default=1519460488.607319),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.FloatField(default=1519460488.6078198),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_at',
            field=models.FloatField(default=1519460488.6068313),
        ),
        migrations.AlterModelTable(
            name='blog',
            table='blogs',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
