# Generated by Django 2.0.2 on 2018-02-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180224_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_at',
            field=models.FloatField(default=1519462443.651018),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.FloatField(default=1519462443.6520174),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_at',
            field=models.FloatField(default=1519462443.650518),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
